### ISSUE TITLE
Binary search?

### ISSUE THREAD

**Issue by jmeas** [jmeas/namespace-diff.js#2]
The linear search I'm using right now is *probably* fine, as I anticipate most namespaces will be no more than 10 levels deep. But if I added binary search then this would be pretty great for really large namespaces, too. Binary search is more code, though, so it's a tradeoff of size vs. perf.

I'll leave it at linear search for now, but you should chime in if you have an opinion in either direction.

**Comment by jamesplease** [comment]
Gonna close this as wontfix for now, 'cause I don't see there being perf problems with the current algorithm.
